schema_version = "1.0.0"

# Example of manifest file for a Blender extension
# Change the values according to your extension
id = "armature_pie"
version = "1.1.2"
name = "Armature Pie"
tagline = "Pick Armatures Comfortably & Solo Collection By Pie Menu"
maintainer = "OuChiang"

type = "add-on"
webside = "https://github.com/OuChiang/armaturePie/issues"
tags = ["Animation", "Rigging"]

blender_version_min = "4.2.0"
license = ['SPDX:GPL-3.0-or-later']

